const EErrors = {
    INVALID_TYPES_ERROR: 1,
    DUPLICATED_ERROR: 2,
    STOCK_ERROR: 3,
    NULL_ERROR: 4,
    PURCHASE_ERROR: 5,
    AUTHENTICATION_ERROR: 6,
    AUTHORIZATION_ERROR: 7
}

export default EErrors